---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  licence: SIL
#  licence_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Crowdsourced, for Fontello project
  github: https://github.com/fontello/brandico.font
  licence: SIL
  licence_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

transform:
  baseline: 0.5

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: brandico

  fullname: Brandico
  familyname: Brandico

  copyright: (C) 2012 by Vitaly Puzrin

  ascent: 800
  descent: 200


glyphs:

  - file: facebook
    code: 0xf300
    css: facebook
    transform:
      offset: 0.05
    meta:
      author: Facebook
      homepage: http://www.facebook.com/brandpermissions/logos.php
    search: [facebook]

  - file: facebook-rect
    code: 0xf301
    css: facebook-rect
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [facebook]

  - file: twitter
    code: 0xf302
    css: twitter
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [twitter]

  - file: twitter-bird
    code: 0xf303
    css: twitter-bird
    transform:
      rescale: 0.9
      offset: 0.05
    meta:
      author: Twitter
      homepage: https://twitter.com/about/resources/logos
    search: [twitter]

  - file: googleplus-rect
    code: 0xf309
    css: googleplus-rect
    transform:
      offset: 0.05
    meta:
      author: Google
      homepage: http://www.google.com/+/business/brand-guidelines.html
    search: [google]

  - file: github-text
    code: 0xf307
    css: github-text
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [github]

  - file: github
    code: 0xf308
    css: github
    transform:
      rescale: 0.9
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [github]

  - file: skype
    code: 0xf30b
    css: skype
    transform:
      offset: 0.05
    meta:
      author: Alex Peattie
      homepage: http://www.alexpeattie.com/projects/justvector_icons/
    search: [skype]

  - file: icq
    code: 0xf304
    css: icq
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [icq]



  - file: yandex
    code: 0xf305
    css: yandex
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [yandex]

  - file: yandex-rect
    code: 0xf306
    css: yandex-rect
    transform:
      offset: 0.05
    meta:
      author: Vitaly Puzrin
      github: https://github.com/puzrin
      twitter: https://twitter.com/puzrin
    search: [yandex]

  - file: vkontakte-rect
    code: 0xf30a
    css: vkontakte-rect
    transform:
      offset: 0.05
    meta:
      author: Vkontakte
      homepage: http://vk.com/help.php?page=about
    search: [google]

  - file: odnoklassniki
    code: 0xf30c
    css: odnoklassniki
    transform:
      offset: 0.05
    meta:
      author: MailRu Group
      homepage: http://corp.mail.ru/communications/odnoklassniki
    search: [odnoklassniki]

  - file: odnoklassniki-rect
    code: 0xf30d
    css: odnoklassniki-rect
    transform:
      offset: 0.05
    meta:
      author: MailRu Group
      homepage: http://corp.mail.ru/communications/odnoklassniki
    search: [odnoklassniki]
